name: Fabric
version: "1.0"
mutual-tls: false

caliper:
  blockchain: fabric
  # command:
  #   start: export FABRIC_VERSION=1.4.4;export FABRIC_CA_VERSION=1.4.4;docker-compose -f networks/fabric/docker-compose/2org1peercouchdb_solo_raft/docker-compose-tls.yaml up -d;sleep 10s
  #   end: docker-compose -f networks/fabric/docker-compose/2org1peercouchdb_solo_raft/docker-compose-tls.yaml down;(test -z \"$(docker ps -aq)\") || docker rm $(docker ps -aq);(test -z \"$(docker images dev* -q)\") || docker rmi $(docker images dev* -q);rm -rf /tmp/hfc-*

info:
  Version: 2.1.0
  Size: 5 Orgs with 1 Peer
  Orderer: Raft
  Distribution: Single Host
  StateDB: CouchDB

clients:
  client0.org1.digiblocks.com:
    client:
      organization: Org1
      credentialStore:
        path: /tmp/hfc-kvs/org1
        cryptoStore:
          path: /tmp/hfc-cvs/org1
      clientPrivateKey:
        path: networks/fabric/crypto-config/peerOrganizations/org1.digiblocks.com/users/User1@org1.digiblocks.com/msp/keystore/priv_sk
      clientSignedCert:
        path: networks/fabric/crypto-config/peerOrganizations/org1.digiblocks.com/users/User1@org1.digiblocks.com/msp/signcerts/User1@org1.digiblocks.com-cert.pem

  client0.org2.digiblocks.com:
    client:
      organization: Org2
      credentialStore:
        path: /tmp/hfc-kvs/org2
        cryptoStore:
          path: /tmp/hfc-cvs/org2
      clientPrivateKey:
        path: networks/fabric/crypto-config/peerOrganizations/org2.digiblocks.com/users/User1@org2.digiblocks.com/msp/keystore/priv_sk
      clientSignedCert:
        path: networks/fabric/crypto-config/peerOrganizations/org2.digiblocks.com/users/User1@org2.digiblocks.com/msp/signcerts/User1@org2.digiblocks.com-cert.pem

  client0.org3.digiblocks.com:
    client:
      organization: Org3
      credentialStore:
        path: /tmp/hfc-kvs/org3
        cryptoStore:
          path: /tmp/hfc-cvs/org3
      clientPrivateKey:
        path: networks/fabric/crypto-config/peerOrganizations/org3.digiblocks.com/users/User1@org3.digiblocks.com/msp/keystore/priv_sk
      clientSignedCert:
        path: networks/fabric/crypto-config/peerOrganizations/org3.digiblocks.com/users/User1@org3.digiblocks.com/msp/signcerts/User1@org3.digiblocks.com-cert.pem

  client0.org4.digiblocks.com:
    client:
      organization: Org4
      credentialStore:
        path: /tmp/hfc-kvs/org4
        cryptoStore:
          path: /tmp/hfc-cvs/org4
      clientPrivateKey:
        path: networks/fabric/crypto-config/peerOrganizations/org4.digiblocks.com/users/User1@org4.digiblocks.com/msp/keystore/priv_sk
      clientSignedCert:
        path: networks/fabric/crypto-config/peerOrganizations/org4.digiblocks.com/users/User1@org4.digiblocks.com/msp/signcerts/User1@org4.digiblocks.com-cert.pem

  client0.org5.digiblocks.com:
    client:
      organization: Org5
      credentialStore:
        path: /tmp/hfc-kvs/org5
        cryptoStore:
          path: /tmp/hfc-cvs/org5
      clientPrivateKey:
        path: networks/fabric/crypto-config/peerOrganizations/org5.digiblocks.com/users/User1@org5.digiblocks.com/msp/keystore/priv_sk
      clientSignedCert:
        path: networks/fabric/crypto-config/peerOrganizations/org5.digiblocks.com/users/User1@org5.digiblocks.com/msp/signcerts/User1@org5.digiblocks.com-cert.pem

channels:
  mychannel:
    # configBinary: networks/fabric/pavan-v2.1/mychannel.tx
    created: true
    contracts: [{ "id": "identitycontract", "version": "1.0" }, { "id": "deccontract", "version": "1.0" }]
    definition:
      capabilities: []
      consortium: "SampleConsortium"
      msps: ["Org1MSP", "Org2MSP", "Org3MSP","Org4MSP", "Org5MSP"]
      version: 0
    orderers:
      - orderer.digiblocks.com
      - orderer2.digiblocks.com
      - orderer3.digiblocks.com
      - orderer4.digiblocks.com
      - orderer5.digiblocks.com
    peers:
      peer0.org1.digiblocks.com:
        eventSource: true
      peer0.org2.digiblocks.com:
        eventSource: true
      peer0.org3.digiblocks.com:
        eventSource: true
      peer0.org4.digiblocks.com:
        eventSource: true
      peer0.org5.digiblocks.com:
        eventSource: true

    # contracts:
    #   - id: identitycontract
    #     contractID: identitycontract
    #     version: "1.0"

organizations:
  Org1:
    mspid: Org1MSP
    peers:
      - peer0.org1.digiblocks.com
      #- peer1.org1.digiblocks.com
    certificateAuthorities:
      - ca.org1.digiblocks.com
    adminPrivateKey:
      path: networks/fabric/crypto-config/peerOrganizations/org1.digiblocks.com/users/Admin@org1.digiblocks.com/msp/keystore/priv_sk
    signedCert:
      path: networks/fabric/crypto-config/peerOrganizations/org1.digiblocks.com/users/Admin@org1.digiblocks.com/msp/signcerts/Admin@org1.digiblocks.com-cert.pem

  Org2:
    mspid: Org2MSP
    peers:
      - peer0.org2.digiblocks.com
      #- peer1.org2.digiblocks.com
    certificateAuthorities:
      - ca.org2.digiblocks.com
    adminPrivateKey:
      path: networks/fabric/crypto-config/peerOrganizations/org2.digiblocks.com/users/Admin@org2.digiblocks.com/msp/keystore/priv_sk
    signedCert:
      path: networks/fabric/crypto-config/peerOrganizations/org2.digiblocks.com/users/Admin@org2.digiblocks.com/msp/signcerts/Admin@org2.digiblocks.com-cert.pem

  Org3:
    mspid: Org3MSP
    peers:
      - peer0.org3.digiblocks.com
      #- peer1.org3.digiblocks.com
    certificateAuthorities:
      - ca.org3.digiblocks.com
    adminPrivateKey:
      path: networks/fabric/crypto-config/peerOrganizations/org3.digiblocks.com/users/Admin@org3.digiblocks.com/msp/keystore/priv_sk
    signedCert:
      path: networks/fabric/crypto-config/peerOrganizations/org3.digiblocks.com/users/Admin@org3.digiblocks.com/msp/signcerts/Admin@org3.digiblocks.com-cert.pem

  Org4:
    mspid: Org4MSP
    peers:
      - peer0.org4.digiblocks.com
      #- peer1.org4.digiblocks.com
    certificateAuthorities:
      - ca.org4.digiblocks.com
    adminPrivateKey:
      path: networks/fabric/crypto-config/peerOrganizations/org4.digiblocks.com/users/Admin@org4.digiblocks.com/msp/keystore/priv_sk
    signedCert:
      path: networks/fabric/crypto-config/peerOrganizations/org4.digiblocks.com/users/Admin@org4.digiblocks.com/msp/signcerts/Admin@org4.digiblocks.com-cert.pem

  Org5:
    mspid: Org5MSP
    peers:
      - peer0.org5.digiblocks.com
      #- peer1.org5.digiblocks.com
    certificateAuthorities:
      - ca.org5.digiblocks.com
    adminPrivateKey:
      path: networks/fabric/crypto-config/peerOrganizations/org5.digiblocks.com/users/Admin@org5.digiblocks.com/msp/keystore/priv_sk
    signedCert:
      path: networks/fabric/crypto-config/peerOrganizations/org5.digiblocks.com/users/Admin@org5.digiblocks.com/msp/signcerts/Admin@org5.digiblocks.com-cert.pem


orderers:
  orderer.digiblocks.com:
    url: grpcs://localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer.digiblocks.com
    tlsCACerts:
      path: networks/fabric/crypto-config/ordererOrganizations/digiblocks.com/orderers/orderer.digiblocks.com/msp/tlscacerts/tlsca.digiblocks.com-cert.pem
  orderer2.digiblocks.com:
    url: grpcs://localhost:8050
    grpcOptions:
      ssl-target-name-override: orderer2.digiblocks.com
    tlsCACerts:
      path: networks/fabric/crypto-config/ordererOrganizations/digiblocks.com/orderers/orderer2.digiblocks.com/msp/tlscacerts/tlsca.digiblocks.com-cert.pem
  orderer3.digiblocks.com:
    url: grpcs://localhost:9050
    grpcOptions:
      ssl-target-name-override: orderer3.digiblocks.com
    tlsCACerts:
      path: networks/fabric/crypto-config/ordererOrganizations/digiblocks.com/orderers/orderer3.digiblocks.com/msp/tlscacerts/tlsca.digiblocks.com-cert.pem

  orderer4.digiblocks.com:
    url: grpcs://localhost:10050
    grpcOptions:
      ssl-target-name-override: orderer4.digiblocks.com
    tlsCACerts:
      path: networks/fabric/crypto-config/ordererOrganizations/digiblocks.com/orderers/orderer4.digiblocks.com/msp/tlscacerts/tlsca.digiblocks.com-cert.pem

  orderer5.digiblocks.com:
    url: grpcs://localhost:11050
    grpcOptions:
      ssl-target-name-override: orderer5.digiblocks.com
    tlsCACerts:
      path: networks/fabric/crypto-config/ordererOrganizations/digiblocks.com/orderers/orderer5.digiblocks.com/msp/tlscacerts/tlsca.digiblocks.com-cert.pem

peers:
  peer0.org1.digiblocks.com:
    url: grpcs://localhost:7051
    grpcOptions:
      ssl-target-name-override: peer0.org1.digiblocks.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/crypto-config/peerOrganizations/org1.digiblocks.com/peers/peer0.org1.digiblocks.com/msp/tlscacerts/tlsca.org1.digiblocks.com-cert.pem

  # peer1.org1.digiblocks.com:
  #   url: grpcs://localhost:8051
  #   grpcOptions:
  #     ssl-target-name-override: peer1.org1.digiblocks.com
  #     grpc.keepalive_time_ms: 600000
  #   tlsCACerts:
  #     path: networks/fabric/crypto-config/peerOrganizations/org1.digiblocks.com/peers/peer1.org1.digiblocks.com/msp/tlscacerts/tlsca.org1.digiblocks.com-cert.pem

  peer0.org2.digiblocks.com:
    url: grpcs://localhost:9051
    grpcOptions:
      ssl-target-name-override: peer0.org2.digiblocks.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/crypto-config/peerOrganizations/org2.digiblocks.com/peers/peer0.org2.digiblocks.com/msp/tlscacerts/tlsca.org2.digiblocks.com-cert.pem
  # peer1.org2.digiblocks.com:
  #   url: grpcs://localhost:10051
  #   grpcOptions:
  #     ssl-target-name-override: peer1.org2.digiblocks.com
  #     grpc.keepalive_time_ms: 600000
  #   tlsCACerts:
  #     path: networks/fabric/crypto-config/peerOrganizations/org2.digiblocks.com/peers/peer1.org2.digiblocks.com/msp/tlscacerts/tlsca.org2.digiblocks.com-cert.pem

  peer0.org3.digiblocks.com:
    url: grpcs://localhost:11051
    grpcOptions:
      ssl-target-name-override: peer0.org3.digiblocks.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/crypto-config/peerOrganizations/org3.digiblocks.com/peers/peer0.org3.digiblocks.com/msp/tlscacerts/tlsca.org3.digiblocks.com-cert.pem
  # peer1.org3.digiblocks.com:
  #   url: grpcs://localhost:12051
  #   grpcOptions:
  #     ssl-target-name-override: peer1.org3.digiblocks.com
  #     grpc.keepalive_time_ms: 600000
  #   tlsCACerts:
  #     path: networks/fabric/crypto-config/peerOrganizations/org3.digiblocks.com/peers/peer1.org3.digiblocks.com/msp/tlscacerts/tlsca.org3.digiblocks.com-cert.pem

  peer0.org4.digiblocks.com:
    url: grpcs://localhost:13051
    grpcOptions:
      ssl-target-name-override: peer0.org4.digiblocks.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/crypto-config/peerOrganizations/org4.digiblocks.com/peers/peer0.org4.digiblocks.com/msp/tlscacerts/tlsca.org4.digiblocks.com-cert.pem
  # peer1.org4.digiblocks.com:
  #   url: grpcs://localhost:14051
  #   grpcOptions:
  #     ssl-target-name-override: peer1.org4.digiblocks.com
  #     grpc.keepalive_time_ms: 600000
  #   tlsCACerts:
  #     path: networks/fabric/crypto-config/peerOrganizations/org4.digiblocks.com/peers/peer1.org4.digiblocks.com/msp/tlscacerts/tlsca.org4.digiblocks.com-cert.pem

  peer0.org5.digiblocks.com:
    url: grpcs://localhost:15051
    grpcOptions:
      ssl-target-name-override: peer0.org5.digiblocks.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/crypto-config/peerOrganizations/org5.digiblocks.com/peers/peer0.org5.digiblocks.com/msp/tlscacerts/tlsca.org5.digiblocks.com-cert.pem
  # peer1.org5.digiblocks.com:
  #   url: grpcs://localhost:16051
  #   grpcOptions:
  #     ssl-target-name-override: peer1.org5.digiblocks.com
  #     grpc.keepalive_time_ms: 600000
  #   tlsCACerts:
  #     path: networks/fabric/crypto-config/peerOrganizations/org5.digiblocks.com/peers/peer1.org5.digiblocks.com/msp/tlscacerts/tlsca.org5.digiblocks.com-cert.pem


certificateAuthorities:
  ca.org1.digiblocks.com:
    url: https://localhost:7054
    httpOptions:
      verify: false
    tlsCACerts:
      path: networks/fabric/crypto-config/peerOrganizations/org1.digiblocks.com/tlsca/tlsca.org1.digiblocks.com-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw

  ca.org2.digiblocks.com:
    url: https://localhost:8054
    httpOptions:
      verify: false
    tlsCACerts:
      path: networks/fabric/crypto-config/peerOrganizations/org2.digiblocks.com/tlsca/tlsca.org2.digiblocks.com-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
  
  ca.org3.digiblocks.com:
    url: https://localhost:9054
    httpOptions:
      verify: false
    tlsCACerts:
      path: networks/fabric/crypto-config/peerOrganizations/org3.digiblocks.com/tlsca/tlsca.org3.digiblocks.com-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
        
  ca.org4.digiblocks.com:
    url: https://localhost:10054
    httpOptions:
      verify: false
    tlsCACerts:
      path: networks/fabric/crypto-config/peerOrganizations/org4.digiblocks.com/tlsca/tlsca.org4.digiblocks.com-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw

  ca.org5.digiblocks.com:
    url: https://localhost:11054
    httpOptions:
      verify: false
    tlsCACerts:
      path: networks/fabric/crypto-config/peerOrganizations/org5.digiblocks.com/tlsca/tlsca.org5.digiblocks.com-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
