#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Fabric
version: "1.0"

caliper:
    blockchain: fabric
    # sutOptions :
    #    mutualTls: true

channels:
  - channelName: mychannel
    contracts:
    - id: identitycontract
      contractID: identitycontract
    - id: modelcontract
      contractID: modelcontract

clients:
  client0.org1.digiblocks.com:
    client:
      organization: Org1
      credentialStore:
        path: /tmp/hfc-kvs/org1
        cryptoStore:
          path: /tmp/hfc-cvs/org1
      clientPrivateKey:
        path: networks/fabric/crypto-config/peerOrganizations/org1.digiblocks.com/users/User1@org1.digiblocks.com/msp/keystore/priv_sk
      clientSignedCert:
        path: networks/fabric/crypto-config/peerOrganizations/org1.digiblocks.com/users/User1@org1.digiblocks.com/msp/signcerts/User1@org1.digiblocks.com-cert.pem

  client0.org2.digiblocks.com:
    client:
      organization: Org2
      credentialStore:
        path: /tmp/hfc-kvs/org2
        cryptoStore:
          path: /tmp/hfc-cvs/org2
      clientPrivateKey:
        path: networks/fabric/crypto-config/peerOrganizations/org2.digiblocks.com/users/User1@org2.digiblocks.com/msp/keystore/priv_sk
      clientSignedCert:
        path: networks/fabric/crypto-config/peerOrganizations/org2.digiblocks.com/users/User1@org2.digiblocks.com/msp/signcerts/User1@org2.digiblocks.com-cert.pem

  client0.org3.digiblocks.com:
    client:
      organization: Org3
      credentialStore:
        path: /tmp/hfc-kvs/org3
        cryptoStore:
          path: /tmp/hfc-cvs/org3
      clientPrivateKey:
        path: networks/fabric/crypto-config/peerOrganizations/org3.digiblocks.com/users/User1@org3.digiblocks.com/msp/keystore/priv_sk
      clientSignedCert:
        path: networks/fabric/crypto-config/peerOrganizations/org3.digiblocks.com/users/User1@org3.digiblocks.com/msp/signcerts/User1@org3.digiblocks.com-cert.pem

  client0.org4.digiblocks.com:
    client:
      organization: Org4
      credentialStore:
        path: /tmp/hfc-kvs/org4
        cryptoStore:
          path: /tmp/hfc-cvs/org4
      clientPrivateKey:
        path: networks/fabric/crypto-config/peerOrganizations/org4.digiblocks.com/users/User1@org4.digiblocks.com/msp/keystore/priv_sk
      clientSignedCert:
        path: networks/fabric/crypto-config/peerOrganizations/org4.digiblocks.com/users/User1@org4.digiblocks.com/msp/signcerts/User1@org4.digiblocks.com-cert.pem

  client0.org5.digiblocks.com:
    client:
      organization: Org5
      credentialStore:
        path: /tmp/hfc-kvs/org5
        cryptoStore:
          path: /tmp/hfc-cvs/org5
      clientPrivateKey:
        path: networks/fabric/crypto-config/peerOrganizations/org5.digiblocks.com/users/User1@org5.digiblocks.com/msp/keystore/priv_sk
      clientSignedCert:
        path: networks/fabric/crypto-config/peerOrganizations/org5.digiblocks.com/users/User1@org5.digiblocks.com/msp/signcerts/User1@org5.digiblocks.com-cert.pem


organizations:
  - mspid: Org1MSP
    identities:
      certificates:
      - name: 'client0.org1.digiblocks.com'
        clientPrivateKey:
          path: networks/fabric/crypto-config/peerOrganizations/org1.digiblocks.com/users/User1@org1.digiblocks.com/msp/keystore/priv_sk
        clientSignedCert:
          path: networks/fabric/crypto-config/peerOrganizations/org1.digiblocks.com/users/User1@org1.digiblocks.com/msp/signcerts/User1@org1.digiblocks.com-cert.pem
    connectionProfile:
      path: 'networks/fabric/crypto-config/org1.yaml'
      discover: false

  - mspid: Org2MSP
    identities:
      certificates:
      - name: 'client0.org2.digiblocks.com'
        clientPrivateKey:
          path: networks/fabric/crypto-config/peerOrganizations/org2.digiblocks.com/users/User1@org2.digiblocks.com/msp/keystore/priv_sk
        clientSignedCert:
          path: networks/fabric/crypto-config/peerOrganizations/org2.digiblocks.com/users/User1@org2.digiblocks.com/msp/signcerts/User1@org2.digiblocks.com-cert.pem
    connectionProfile:
      path: 'networks/fabric/crypto-config/org2.yaml'
      discover: false

  - mspid: Org3MSP
    identities:
      certificates:
      - name: 'client0.org3.digiblocks.com'
        clientPrivateKey:
          path: networks/fabric/crypto-config/peerOrganizations/org3.digiblocks.com/users/User1@org3.digiblocks.com/msp/keystore/priv_sk
        clientSignedCert:
          path: networks/fabric/crypto-config/peerOrganizations/org3.digiblocks.com/users/User1@org3.digiblocks.com/msp/signcerts/User1@org3.digiblocks.com-cert.pem
    connectionProfile:
      path: 'networks/fabric/crypto-config/org3.yaml'
      discover: false

  - mspid: Org4MSP
    identities:
      certificates:
      - name: 'client0.org4.digiblocks.com'
        clientPrivateKey:
          path: networks/fabric/crypto-config/peerOrganizations/org4.digiblocks.com/users/User1@org4.digiblocks.com/msp/keystore/priv_sk
        clientSignedCert:
          path: networks/fabric/crypto-config/peerOrganizations/org4.digiblocks.com/users/User1@org4.digiblocks.com/msp/signcerts/User1@org4.digiblocks.com-cert.pem
    connectionProfile:
      path: 'networks/fabric/crypto-config/org4.yaml'
      discover: false

  - mspid: Org5MSP
    identities:
      certificates:
      - name: 'client0.org5.digiblocks.com'
        clientPrivateKey:
          path: networks/fabric/crypto-config/peerOrganizations/org5.digiblocks.com/users/User1@org5.digiblocks.com/msp/keystore/priv_sk
        clientSignedCert:
          path: networks/fabric/crypto-config/peerOrganizations/org5.digiblocks.com/users/User1@org5.digiblocks.com/msp/signcerts/User1@org5.digiblocks.com-cert.pem
    connectionProfile:
      path: 'networks/fabric/crypto-config/org5.yaml'
      discover: false
  